server:
  port: ${PORT:8304}

spring:
 security:
    enabled: false

security:
  basic:
    enabled: false

#spring:
#  session:
#    store-type: redis

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  ignoredServices: '*'
  routes:
    proxy:
      path: /proxy/**
      sensitive-headers: Cookie,Set-Cookie
      serviceId: proxy
      url: http://localhost:8304
    data-retriever:
      path: /data-retriever/**
      sensitive-headers: Cookie,Set-Cookie
      serviceId: data-retriever
      url: http://localhost:8305
    buy-service:
      path: /buy-service/**
      sensitive-headers: Cookie,Set-Cookie
      serviceId: buy-service
      url: http://localhost:8301
    payment:
      path: /payment/**
      sensitive-headers: Cookie,Set-Cookie
      serviceId: payment
      url: http://localhost:8087
    sidecar:
      path: /sidecar/**
      sensitive-headers: Cookie,Set-Cookie
      serviceId: sidecar
      url: http://localhost:5000

#security:
#  user:
#    name: root
#    password: password
#  oauth2:
#    client:
#      accessTokenUri: http://localhost:8304/uua/oauth/token #8765
#      userAuthorizationUri: http://localhost:8304/uua/oauth/authorize
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: http://localhost:8304/uaa/user
#      preferTokenInfo: false
#  sessions: ALWAYS

eureka:
  client:
    serviceUrl:
      defaultZone:   http://localhost:8302/eureka/

#security:
#  basic:
#      enabled: false
#  oauth2:
#    client:
#      accessTokenUri: http://localhost:8304/uua/oauth/token
#      userAuthorizationUri: http://localhost:8304/uua/oauth/authorize
#      #clientAuthenticationScheme: form
#      clientId: acme
#      clientSecret: acmesecret
#    resource:
#      userInfoUri: http://localhost:8304/uaa/user
#      preferTokenInfo: false
#  sessions: ALWAYS

#proxy:
#  auth:
#    routes:
#      data-retriever: oauth2
#      buy-service: oauth2
#      #sidecar: oauth2

